baseURL = "https://quotesandsayings.net/"
title = "Quotes and Sayings"
theme = "quotes-and-sayings"
enableRobotsTXT = true
enableGitInfo = true

[languages.en]
languageName = "english"
languageDirection = "ltr"
[languages.ar]
languageName = "عربية"
languageDirection = "rtl"
title = "أقوال و اقتباسات"


